name: Deploy to Azure

on:
  workflow_run:
    workflows: ["Build Node.js app"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # JWT のリクエストに必要
      contents: read # actions/checkout に必要
      

    steps:
      - name: Download artifact from build
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build_dev.yml
          workflow_conclusion: success
          name: node-app
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.APP_SERVICE_NAME }}
          resource-group-name: 'example-resources'
          slot-name: ''
          package: frontend/build 

