name: Build and deploy Node.js app to Azure Web App - dot-app-acb6de1bcb7be153

on:
  push:
    branches:
      - release_test_amane
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # actions/checkout に必要

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies, build, and test
        working-directory: ./frontend
        run: |
          echo "Current directory: $(pwd)"
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip frontend/build # build フォルダのみ圧縮

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # JWT のリクエストに必要
      contents: read # actions/checkout に必要

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      # 2. Debug: List web apps to check if the resource is visible from the runner
      - name: Check if Azure Web App exists
        run: |
          az webapp list --query "[?name=='dot-app-acb6de1bcb7be153'].{Name:name, ResourceGroup:resourceGroup}" --output table

      # 3. Debug: Show detailed info for the specific web app to ensure it's accessible
      - name: Check specific Azure Web App details
        run: |
          az webapp show --name dot-app-acb6de1bcb7be153 --resource-group example-resources --debug

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dot-app-acb6de1bcb7be153'
          resource-group-name: 'example-resources'
          slot-name: ''
          package: frontend/build 
