jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # 現在の作業ディレクトリを表示
      - name: Check current working directory
        run: echo "Current directory: $(pwd)"

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 現在の作業ディレクトリを確認
      - name: Check directory before running npm commands
        run: |
          echo "Current directory before npm commands: $(pwd)"
          ls -la  # フォルダ内のファイルも確認

      - name: npm install, build, and test
        working-directory: ./frontend  # `frontend` フォルダに変更
        run: |
          echo "Current directory during npm install: $(pwd)"
          npm install
          npm run build --if-present
          npm run test --if-present

      # zipを作成
      - name: Zip artifact for deployment
        working-directory: ./frontend
        run: |
          echo "Current directory before zipping: $(pwd)"
          zip release.zip ./* -r

      # アーティファクトをアップロード
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
